#!/bin/bash

set_tab_name "cyberchef"

sleep 0.5

type_command "docker run --rm --name cyberchef -it ghcr.io/gchq/cyberchef:latest"
type_newline

split_term_horz

sleep 1.5

type_command "CONTAINER_IP=\$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' cyberchef)"
type_newline

sleep 0.5

type_command "firefox http://\${CONTAINER_IP}"
type_newline
